In [46]:
import numpy as np

# Класс, методы которого реализуют все стандартные быстрые унарные математические операции 
# над элементами выбранного среза двухмерного массива, обнуляя при
# этом все элементы, не относящиеся к срезу; по умолчанию (если срез не задан) быстрые унарные
# математические операции выполняются над всеми элементами массива

class Flat:
    
    def __init__(self, array, slice=None):
        
        self.array = array
        
        self.methods = ['abs', 'fabs',
                        'square',
                        'exp',
                        'log','log10','log2','log1p',
                        'sign'
                        'ceil',
                        'floor',
                        'rint',
                        'modf',
                        'isnan',
                        'isfinite','isinf',
                        'cos','cosh','sin','sinh','tan','tanh',
                        'arccos','arccosh','arcsin', 'arcsinh','arctan','arctanh',
                        'logical_not']

        if slice is None:
            self.negative = np.full(self.array.shape, True)
        else:
            self.negative = np.zeros(self.array.shape, dtype=bool)
            try:
                self.negative[int(slice[0]):int(slice[1]), int(slice[2]):int(slice[3])] = True
            except(IndexError, ValueError): # incorrect slice values == without slice
                self.negative = np.full(self.array.shape, True)
                
            self.add_methods()
            
    def sqrt(self):
        # виконуєм операцію тільки в тих позиціях, де в відповідних позиціях 
        # масиву self.negative значення True
        return np.sqrt(np.abs(self.array, where=self.negative, out=np.zeros(self.array.shape)))
            
    def add_methods(self):

        local_variables = {}
        
        for method in self.methods:
            code = f"def {method}(self): return np.{method}(self.array, where=self.negative, out=np.zeros(self.array.shape))"    
            exec(code, None, local_variables)
            
        for name, value in local_variables.items():
            setattr(Flat, name, value)

    # преобразует исходный двумерный массив в трехмерный, копируя исходный
    # двухмерный массив вдоль третьей оси (axis=2) заданное количество раз
    def add_dimension(self, num=5):
        return np.repeat(self.array[..., np.newaxis], num, axis=2)
        


In [47]:
np.random.seed(123)
array = np.random.randn(5, 5)
print(array)

[[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]
 [ 1.65143654 -2.42667924 -0.42891263  1.26593626 -0.8667404 ]
 [-0.67888615 -0.09470897  1.49138963 -0.638902   -0.44398196]
 [-0.43435128  2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904 -1.25388067]]


In [48]:
f1 = Flat(array,(1,3,1,3))
f2 = Flat(array)
f3 = Flat(array,(2,4,1,4))

In [49]:
print(f1.tan())

[[ 0.          0.          0.          0.          0.        ]
 [ 0.          0.86810835 -0.4573056   0.          0.        ]
 [ 0.         -0.09499316 12.56691563  0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]


In [50]:
print(f2.abs())

[[1.0856306  0.99734545 0.2829785  1.50629471 0.57860025]
 [1.65143654 2.42667924 0.42891263 1.26593626 0.8667404 ]
 [0.67888615 0.09470897 1.49138963 0.638902   0.44398196]
 [0.43435128 2.20593008 2.18678609 1.0040539  0.3861864 ]
 [0.73736858 1.49073203 0.93583387 1.17582904 1.25388067]]


In [51]:
print(f3.sin())

[[ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.         -0.09456745  0.99684894 -0.59631438  0.        ]
 [ 0.          0.80499235  0.816202    0.84365439  0.        ]
 [ 0.          0.          0.          0.          0.        ]]


In [60]:
print(f3.sqrt())

[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.30774822 1.22122464 0.79931345 0.        ]
 [0.         1.48523738 1.47877858 1.0020249  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [59]:
print(f2.add_dimension())

[[[-1.0856306  -1.0856306  -1.0856306  -1.0856306  -1.0856306 ]
  [ 0.99734545  0.99734545  0.99734545  0.99734545  0.99734545]
  [ 0.2829785   0.2829785   0.2829785   0.2829785   0.2829785 ]
  [-1.50629471 -1.50629471 -1.50629471 -1.50629471 -1.50629471]
  [-0.57860025 -0.57860025 -0.57860025 -0.57860025 -0.57860025]]

 [[ 1.65143654  1.65143654  1.65143654  1.65143654  1.65143654]
  [-2.42667924 -2.42667924 -2.42667924 -2.42667924 -2.42667924]
  [-0.42891263 -0.42891263 -0.42891263 -0.42891263 -0.42891263]
  [ 1.26593626  1.26593626  1.26593626  1.26593626  1.26593626]
  [-0.8667404  -0.8667404  -0.8667404  -0.8667404  -0.8667404 ]]

 [[-0.67888615 -0.67888615 -0.67888615 -0.67888615 -0.67888615]
  [-0.09470897 -0.09470897 -0.09470897 -0.09470897 -0.09470897]
  [ 1.49138963  1.49138963  1.49138963  1.49138963  1.49138963]
  [-0.638902   -0.638902   -0.638902   -0.638902   -0.638902  ]
  [-0.44398196 -0.44398196 -0.44398196 -0.44398196 -0.44398196]]

 [[-0.43435128 -0.43435128 -0.4343